title: h3llh0und
markdown: kramdown
url: ""
baseurl: "/blog"

# for atom feed
author:
  name: h3llh0und
  email: nckbr@proton.me

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
